import SwiftUI

/// Hand-authored pixel-art emblems for team crests.
///
/// Same IP footing as `TeamGlyph`: every sprite depicts the ordinary thing the
/// team is *named* after — a flame, a shark tooth, a maple leaf — drawn from
/// scratch here, never traced from or fitted to a club's actual emblem. Where a
/// faithful depiction would have to be the club's own artwork, the sprite shows
/// the city instead: Chicago is its skyline, never the head on the sweater.
/// Being authored as code there's also no generated-art provenance question and
/// nothing to license or attribute.
///
/// A sprite is a 24x24 grid of characters, one per pixel, and every color comes
/// from `TeamInfo` — so the art themes itself per team and follows a palette
/// retune for free.
///
///   `.` transparent   `X` body      `L` body, lightened
///   `D` body, darkened                `E` cut out to the disc color
///
/// `E` is what makes eyes and visor slits read: it paints the crest's own
/// background back over the art, so the shape looks punched through.
///
/// Authored with `Tools/render_sprites.py`, which draws these grids at three
/// scales. Judge a change there, not in the simulator — screenshots are
/// downscaled well past what 24x24 art can be assessed at, and shapes that
/// look fine blown up routinely turn to mush at crest size.
struct TeamSprite {
    let rows: [String]

    /// Grid resolution — sprites are square, so this is both width and height.
    var resolution: Int { rows.count }

    static func sprite(for abbrev: String) -> TeamSprite? {
        sprites[abbrev.uppercased()]
    }

    private static let sprites: [String: TeamSprite] = [
        // MARK: Atlantic
        "BOS": TeamSprite(rows: [   // bear
            "........................",
            ".XXXX..............XXXX.",
            "XXXXXX............XXXXXX",
            "XXXXXX............XXXXXX",
            "XXXXXXX..........XXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "..XXXXXXXXXXXXXXXXXXXX..",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXDDDDXXXXXXXXXXXXDDDDXX",
            "XXXDDDDXXXXXXXXXXDDDDXXX",
            "XXXXEEXXXXXXXXXXXXEEXXXX",
            "XXXXEEXXXXXXXXXXXXEEXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "..XXXXXXLLLLLLLLXXXXXX..",
            "..XXXXXLLLLLLLLLLXXXXX..",
            "...XXXXLLLDDDDLLLXXXX...",
            "...XXXXXLLDDDDLLXXXXX...",
            "....XXXXXLLLLLLXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            ".......XXXXXXXXXX.......",
            "........................",
        ]),
        "BUF": TeamSprite(rows: [   // crossed sabres
            "........................",
            "........................",
            ".XX..................XX.",
            "..XX................XX..",
            "...XX..............XX...",
            "....XX............XX....",
            ".....XX..........XX.....",
            "......XX........XX......",
            ".......XX......XX.......",
            "........XX....XX........",
            ".........XX..XX.........",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XX..XX.........",
            "........XX....XX........",
            ".......XX......XX.......",
            "......XX........XX......",
            ".....XX..........XX.....",
            "....XX............XX....",
            "...XX..............XX...",
            "..DD................DD..",
            ".DDD................DDD.",
            "........................",
            "........................",
        ]),
        "DET": TeamSprite(rows: [   // cog — Motor City
            "........................",
            "........................",
            ".......XX......XX.......",
            ".......XX......XX.......",
            "....XXXXXXXXXXXXXXXX....",
            "....XXXXXXXXXXXXXXXX....",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXEEEEXXXXXXXX..",
            "..XXXXXXXEEEEEEXXXXXXX..",
            "XXXXXXXXXEEEEEEXXXXXXXXX",
            "XXXXXXXXXEEEEEEXXXXXXXXX",
            "..XXXXXXXEEEEEEXXXXXXX..",
            "..XXXXXXXXEEEEXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "....XXXXXXXXXXXXXXXX....",
            "....XXXXXXXXXXXXXXXX....",
            ".......XX......XX.......",
            ".......XX......XX.......",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "FLA": TeamSprite(rows: [   // panther
            "........................",
            "..XX................XX..",
            "..XXX..............XXX..",
            "..XXXX............XXXX..",
            "..XXXXX..........XXXXX..",
            "..XXXXXXX......XXXXXXX..",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "XXXEEXXXXXXXXXXXXXXEEXXX",
            "XXXEEXXXXXXXXXXXXXXEEXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "..XXXXXXXXDDDDXXXXXXXX..",
            "..XXXXXXXXXDDXXXXXXXXX..",
            "...XXXXXXXXXXXXXXXXXX...",
            "....XXXXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            "......XXXXXXXXXXXX......",
            ".......XXXXXXXXXX.......",
            "........................",
            "........................",
        ]),
        "MTL": TeamSprite(rows: [   // fleur-de-lis — Quebec, not the club monogram
            "........................",
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            "....X....XXXXXX....X....",
            "...XX....XXXXXX....XX...",
            "..XXX....XXXXXX....XXX..",
            "..XXX....XXXXXX....XXX..",
            "..XXXX...XXXXXX...XXXX..",
            "...XXXX..XXXXXX..XXXX...",
            "....XXXXXXXXXXXXXXXX....",
            "......XXXXXXXXXXXX......",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "........................",
            "........................",
        ]),
        "OTT": TeamSprite(rows: [   // senate temple
            "........................",
            "........................",
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            ".....XX..XX..XX..XX.....",
            ".....XX..XX..XX..XX.....",
            ".....XX..XX..XX..XX.....",
            ".....XX..XX..XX..XX.....",
            ".....XX..XX..XX..XX.....",
            ".....XX..XX..XX..XX.....",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "........................",
            "........................",
            "........................",
        ]),
        "TBL": TeamSprite(rows: [   // lightning
            "........................",
            "........................",
            ".........XXXXXX.........",
            "........XXXXXX..........",
            ".......XXXXXX...........",
            "......XXXXXX............",
            ".....XXXXXX.............",
            "....XXXXXXXXXXXX........",
            "...XXXXXXXXXXXXXX.......",
            "..XXXXXXXXXXXXXXXX......",
            "..........XXXXXX........",
            ".........XXXXXX.........",
            "........XXXXXX..........",
            ".......XXXXXX...........",
            "......XXXXXX............",
            ".....XXXXXX.............",
            "....XXXXXX..............",
            "...XXXXXX...............",
            "..XXXXX.................",
            "..XXX...................",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "TOR": TeamSprite(rows: [   // maple leaf — the national symbol
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            "..........XXXX..........",
            "....X.....XXXX.....X....",
            "....XX....XXXX....XX....",
            "....XXX..XXXXXX..XXX....",
            "....XXXXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            "X....XXXXXXXXXXXXXX....X",
            "XX..XXXXXXXXXXXXXXXX..XX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "...XXXXXXXXXXXXXXXXXX...",
            "....XXXXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            "......XXXXXXXXXXXX......",
            ".......XXXXXXXXXX.......",
            ".........XXXXXX.........",
            "...........XX...........",
            "...........XX...........",
            "...........XX...........",
            "........................",
        ]),

        // MARK: Metropolitan
        "CAR": TeamSprite(rows: [   // hurricane
            "........................",
            "........................",
            "........................",
            ".......XXXXXXXXXX.......",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXX..........XXX...",
            "...XXX....XXXXXX....XX..",
            "...XX....XXXXXXXX....XX.",
            "..XX....XXX....XXX....X.",
            "..XX...XX........XX.....",
            "..XX...XX...XX...XX.....",
            "..XX...XX..XXXX..XX.....",
            ".....XX..XXXX...XX...XX.",
            ".....XX...XX....XX...XX.",
            ".X....XXX........XX...XX",
            ".XX....XXX....XXX....XX.",
            "..XX....XXXXXXXX....XX..",
            "...XXX....XXXX....XXX...",
            "....XXXX........XXXX....",
            ".....XXXXXXXXXXXXXX.....",
            ".......XXXXXXXXXX.......",
            "........................",
            "........................",
            "........................",
        ]),
        "CBJ": TeamSprite(rows: [   // regimental chevrons
            "........................",
            "........................",
            "........................",
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            ".......XXXX..XXXX.......",
            "......XXXX....XXXX......",
            ".....XXXX......XXXX.....",
            "....XXXX........XXXX....",
            "...........XX...........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            ".......XXXX..XXXX.......",
            "......XXXX....XXXX......",
            ".....XXXX......XXXX.....",
            "....XXXX........XXXX....",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "NJD": TeamSprite(rows: [   // trident
            "........................",
            "........................",
            "..XX......XXXX......XX..",
            "..XX......XXXX......XX..",
            "..XX......XXXX......XX..",
            "..XX......XXXX......XX..",
            "..XX......XXXX......XX..",
            "..XX......XXXX......XX..",
            "..XX......XXXX......XX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "NYI": TeamSprite(rows: [   // lighthouse
            "........................",
            "........................",
            "........................",
            "..........XXXX..........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            ".......XXXXXXXXXX.......",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "........................",
            "........................",
        ]),
        "NYR": TeamSprite(rows: [   // heraldic shield
            "........................",
            "........................",
            "........................",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "...EEEEEEEEEEEEEEEEEE...",
            "...EEEEEEEEEEEEEEEEEE...",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "....XXXXXXXXXXXXXXXX....",
            "....XXXXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            "......XXXXXXXXXXXX......",
            ".......XXXXXXXXXX.......",
            "........XXXXXXXX........",
            ".........XXXXXX.........",
            "..........XXXX..........",
            "...........XX...........",
            "........................",
            "........................",
            "........................",
        ]),
        "PHI": TeamSprite(rows: [   // Liberty Bell
            "........................",
            "........................",
            "........................",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..........XXXX..........",
            "..........XXXX..........",
            "........................",
            "........................",
            "........................",
        ]),
        "PIT": TeamSprite(rows: [   // penguin
            "........................",
            "........................",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            "......XXXXXXXXXXXX......",
            "......XXXEEXXEEXXX......",
            "......XXXEEXXEEXXX......",
            "......XXXXXXXXXXXX......",
            ".......XXDDDDDDXX.......",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXLLLLLLXXXXX....",
            "...XXXXXLLLLLLLLXXXXX...",
            "...XXXXLLLLLLLLLLXXXX...",
            "..XXXXXLLLLLLLLLLXXXXX..",
            "..XXXXXLLLLLLLLLLXXXXX..",
            "..XXXXXLLLLLLLLLLXXXXX..",
            "..XXXXXLLLLLLLLLLXXXXX..",
            "...XXXXLLLLLLLLLLXXXX...",
            "...XXXXXLLLLLLLLXXXXX...",
            "....XXXXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            "...DDD...DDDDDD...DDD...",
            "........................",
            "........................",
        ]),
        "WSH": TeamSprite(rows: [   // Capitol dome
            "........................",
            "........................",
            "...........XX...........",
            "...........XX...........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            ".XX..XX..XXXXXX..XX..XX.",
            ".XX..XX..XXXXXX..XX..XX.",
            ".XX..XX..XXXXXX..XX..XX.",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "........................",
            "........................",
        ]),

        // MARK: Central
        "CHI": TeamSprite(rows: [   // skyline — deliberately the city, never the head on the sweater
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "..................XX....",
            "..................XX....",
            ".......XX.........XX....",
            ".......XX.........XX....",
            "...XX..XX...XXX...XX....",
            "...XX..XX...XXX...XX..XX",
            "...XX..XX...XXX...XX..XX",
            "...XXXXXX...XXX...XX..XX",
            "XX.XXXXXX.XXXXXXX.XX..XX",
            "XX.XXXXXX.XXXXXXX.XXXXXX",
            "XX.XXXXXX.XXXXXXX.XXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "COL": TeamSprite(rows: [   // avalanche peak
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "...........LL...........",
            "..........LLLL..........",
            "..........LLLL..........",
            ".........LLLLLL.........",
            ".........XLLLLX.........",
            "....X...XXXLLXXX...X....",
            "...XXX.XXXXXXXXXX.XXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "DAL": TeamSprite(rows: [   // star
            "........................",
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "...XXXXXXXXXXXXXXXXXX...",
            "....XXXXXXXXXXXXXXXX....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXX.XXXXXXXX.XXXXX..",
            "..XXXX...XXXXXX...XXXX..",
            ".XXXX.....XXXX.....XXXX.",
            ".XXX......XXXX......XXX.",
            "XX.........XX.........XX",
            "X......................X",
            "........................",
            "........................",
        ]),
        "MIN": TeamSprite(rows: [   // north-woods pine
            "........................",
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "..........XXXX..........",
            "..........XXXX..........",
            "..........XXXX..........",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            "........................",
            "........................",
        ]),
        "NSH": TeamSprite(rows: [   // Music City note
            "........................",
            "........................",
            "........................",
            "..............XXXXXX....",
            "..............XXXXXXX...",
            "..............XXX..XXX..",
            "..............XXX...XXX.",
            "..............XXX...XXX.",
            "..............XXX..XXX..",
            "..............XXXXXX....",
            "..............XXX.......",
            "..............XXX.......",
            "..............XXX.......",
            "..............XXX.......",
            "..............XXX.......",
            ".....XXXXX....XXX.......",
            "...XXXXXXXXX..XXX.......",
            "..XXXXXXXXXXXXXXX.......",
            "..XXXXXXXXXXXXXXX.......",
            "..XXXXXXXXXXXXXX........",
            "...XXXXXXXXXXX..........",
            ".....XXXXXXX............",
            "........................",
            "........................",
        ]),
        "STL": TeamSprite(rows: [   // Gateway Arch
            "........................",
            "........................",
            "........................",
            "..........XXXX..........",
            "........XXXXXXXX........",
            ".......XXX....XXX.......",
            "......XXX......XXX......",
            ".....XXX........XXX.....",
            "....XXX..........XXX....",
            "....XX............XX....",
            "...XXX............XXX...",
            "...XX..............XX...",
            "...XX..............XX...",
            "..XXX..............XXX..",
            "..XX................XX..",
            "..XX................XX..",
            "..XX................XX..",
            "..XX................XX..",
            "..XX................XX..",
            "..XX................XX..",
            "..XX................XX..",
            "........................",
            "........................",
            "........................",
        ]),
        "UTA": TeamSprite(rows: [   // ice-age snowflake
            "........................",
            "........................",
            "..........XXXX..........",
            "..........XXXX..........",
            "...X......XXXX......X...",
            "....XX....XXXX....XX....",
            ".....XX...XXXX...XX.....",
            "......XX..XXXX..XX......",
            ".......XXXXXXXXXX.......",
            "..XX....XXXXXXXX....XX..",
            "...XXXXXXXXXXXXXXXXXX...",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XX....XXXXXXXX....XX..",
            ".......XXXXXXXXXX.......",
            "......XX..XXXX..XX......",
            ".....XX...XXXX...XX.....",
            "....XX....XXXX....XX....",
            "...X......XXXX......X...",
            "..........XXXX..........",
            "..........XXXX..........",
            "........................",
            "........................",
        ]),
        "WPG": TeamSprite(rows: [   // jet
            "........................",
            "........................",
            "........................",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            "......XXXXXXXXXXXX......",
            "......XXXXXXXXXXXX......",
            ".......XXXXXXXXXX.......",
            "..........XXXX..........",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),

        // MARK: Pacific
        "ANA": TeamSprite(rows: [   // duck
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            ".......XXXXXXXX.........",
            "......XXXXXXXXXX........",
            ".....XXXXXXXXXXXX.......",
            ".....XXXXEXXXXXXX.......",
            ".....XXXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXXXXX..",
            "......XXXXXXXXXXXXXXXXX.",
            "......XXXXXXXXXXXXXXXX..",
            ".......XXXXXXXXXX.......",
            "........XXXXXXXX........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "CGY": TeamSprite(rows: [   // flame
            "........................",
            "........................",
            "...........XX...........",
            "..........XXX...........",
            ".........XXXX...........",
            ".........XXXX....XX.....",
            "........XXXXX...XXX.....",
            "........XXXXX..XXXX.....",
            ".......XXXXXXXXXXXX.....",
            "......XXXXXXXXXXXXXX....",
            "......XXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXXXX...",
            ".....XXXXXLLLLXXXXXXX...",
            "....XXXXXLLLLLLXXXXXXX..",
            "....XXXXLLLLLLLLXXXXXX..",
            "....XXXXLLLLLLLLXXXXXX..",
            "....XXXXXLLLLLLXXXXXXX..",
            ".....XXXXXLLLLXXXXXXX...",
            ".....XXXXXXXXXXXXXXXX...",
            "......XXXXXXXXXXXXXX....",
            ".......XXXXXXXXXXXX.....",
            "........XXXXXXXXXX......",
            "........................",
            "........................",
        ]),
        "EDM": TeamSprite(rows: [   // oil drop
            "........................",
            "........................",
            "........................",
            "...........XX...........",
            "...........XX...........",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "....XXXXLLXXXXLLXXXX....",
            "....XXXLLLXXXXLLLXXX....",
            ".....XXXLLXXXXLLXXX.....",
            "......XXXXXXXXXXXX......",
            ".......XXXXXXXXXX.......",
            ".........XXXXXX.........",
            "........................",
            "........................",
            "........................",
        ]),
        "LAK": TeamSprite(rows: [   // crown
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "X.....X....XX....X.....X",
            "XX...XXX...XX...XXX...XX",
            "XXX.XXXXX.XXXX.XXXXX.XXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            ".XXXXXXXXXXXXXXXXXXXXXX.",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "SJS": TeamSprite(rows: [   // shark tooth
            "........................",
            "........................",
            "........................",
            "........................",
            "...........XX...........",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "...XXXXX........XXXXX...",
            "........................",
            "........................",
        ]),
        "SEA": TeamSprite(rows: [   // kraken
            "........................",
            "........................",
            "..........XXXX..........",
            "........XXXXXXXX........",
            ".......XXXXXXXXXX.......",
            "......XXXXEXXEXXXX......",
            "......XXXXEXXEXXXX......",
            "......XXXXXXXXXXXX......",
            ".......XXXXXXXXXX.......",
            "......XXXXXXXXXXXX......",
            ".....XX.XX.XX.XX.XX.....",
            "....XX..XX.XX.XX..XX....",
            "...XX...XX.XX.XX...XX...",
            "..XX....XX.XX.XX....XX..",
            "..XX...XX..XX..XX....XX.",
            ".XX....XX..XX..XX.....XX",
            ".XX...XX...XX...XX....XX",
            "XX....XX...XX...XX.....X",
            "XX...XX....XX....XX.....",
            ".X...XX....XX....XX.....",
            "........................",
            "........................",
            "........................",
            "........................",
        ]),
        "VAN": TeamSprite(rows: [   // whale fluke
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "........................",
            "..........XXXX..........",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "........XXXXXXXX........",
            "......XXXXXXXXXXXX......",
            "....XXXXXXXXXXXXXXXX....",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXX.XXXX.XXXXXXXXX",
            "XXXXXXX....XX....XXXXXXX",
            "XXXXX..............XXXXX",
            "XXX..................XXX",
            "X......................X",
            "........................",
            "........................",
        ]),
        "VGK": TeamSprite(rows: [   // knight's helm
            "........................",
            "........................",
            "........................",
            "..........XXXX..........",
            ".........XXXXXX.........",
            "......XXXXXXXXXXXX......",
            ".....XXXXXXXXXXXXXX.....",
            "....XXXXXXXXXXXXXXXX....",
            "...XXXXXXXXXXXXXXXXXX...",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXXXXXXXXXXXXXXXXXXX..",
            "..XXEXXEXXEXXEXXEXXEXX..",
            "..XXEXXEXXEXXEXXEXXEXX..",
            "..XXEXXEXXEXXEXXEXXEXX..",
            "..XXEXXEXXEXXEXXEXXEXX..",
            "..XXEXXEXXEXXEXXEXXEXX..",
            "...XXXXXXXXXXXXXXXXXX...",
            "....XXXXXXXXXXXXXXXX....",
            ".....XXXXXXXXXXXXXX.....",
            "......XXXXXXXXXXXX......",
            "........................",
            "........................",
            "........................",
        ]),

    ]
}

/// Draws a `TeamSprite` as crisp, unsmoothed pixels.
struct PixelSpriteView: View {
    let sprite: TeamSprite
    /// Main color of the art (the crest's contrast-safe emblem color).
    let ink: Color
    /// The color behind the sprite, painted into `E` pixels as a cut-out.
    let cut: Color

    @Environment(\.displayScale) private var displayScale

    var body: some View {
        Canvas { ctx, size in
            let n = sprite.resolution
            let step = size.width / CGFloat(n)
            // Snap cell edges to whole *device* pixels, not points. A crest is
            // often ~20pt wide, so at 24 cells a point-aligned grid rounds
            // several cells to zero width and visibly mangles the art; at 3x
            // there are still ~2.5 device pixels per cell to land on.
            let scale = max(1, displayScale)
            func snap(_ v: CGFloat) -> CGFloat { (v * scale).rounded() / scale }
            let unit = 1 / scale
            for (r, row) in sprite.rows.enumerated() {
                for (c, ch) in row.enumerated() where ch != "." {
                    let x0 = snap(CGFloat(c) * step)
                    let y0 = snap(CGFloat(r) * step)
                    let x1 = snap(CGFloat(c + 1) * step)
                    let y1 = snap(CGFloat(r + 1) * step)
                    let cell = Path(CGRect(x: x0, y: y0,
                                           width: max(unit, x1 - x0),
                                           height: max(unit, y1 - y0)))
                    switch ch {
                    case "X":
                        ctx.fill(cell, with: .color(ink))
                    case "L":
                        ctx.fill(cell, with: .color(ink))
                        ctx.fill(cell, with: .color(.white.opacity(0.45)))
                    case "D":
                        ctx.fill(cell, with: .color(ink))
                        ctx.fill(cell, with: .color(.black.opacity(0.40)))
                    case "E":
                        ctx.fill(cell, with: .color(cut))
                    default:
                        break
                    }
                }
            }
        }
        .allowsHitTesting(false)
    }
}
